/** example
 * {
  playersByTeam: {
    RBK: { GK: [Array], players: [Array] },
    VLH: { GK: [Array], players: [Array] }
  },
  recaps: {
    '0': {
      periodNumber: 1,
      gameStatsId: 13558,
      status: 'Finished',
      awayTeamId: 'RBK',
      awayTeamName: 'Rögle BK',
      awayG: 1,
      awayPIM: 0,
      awayFOW: 5,
      awaySOG: 9,
      awaySPG: 6,
      awaySaves: 5,
      awayGA: 0,
      awaySavesPerShot: 1,
      awayPP_perc: 0,
      awaySH_perc: 0,
      awayPPG: 0,
      awaySHG: 0,
      awayPPGA: 0,
      awaySHGA: 0,
      awayNumPP: 1,
      awayNumSH: 0,
      awayHits: 7,
      awayPPSOG: 1,
      awayactiontype: 'api',
      awayteamId: 'ee93-ee93uy4oW',
      startDateTime: '',
      endDateTime: '',
      statusString: 'Slut',
      homeTeamId: 'VLH',
      homeTeamName: 'Växjö Lakers',
      homeG: 0,
      homePIM: 2,
      homeFOW: 7,
      homeSOG: 5,
      homeSPG: 3,
      homeSaves: 8,
      homeGA: 1,
      homeSavesPerShot: 0.8888888888888888,
      homePP_perc: 0,
      homeSH_perc: 1,
      homePPG: 0,
      homeSHG: 0,
      homePPGA: 0,
      homeSHGA: 0,
      homeNumPP: 0,
      homeNumSH: 1,
      homeHits: 1,
      homePPSOG: 0,
      homeactiontype: 'api',
      hometeamId: 'fe02-fe02mf1FN'
    },
    '1': {
      periodNumber: 2,
      gameStatsId: 13558,
      status: 'Finished',
      awayTeamId: 'RBK',
      awayTeamName: 'Rögle BK',
      awayG: 0,
      awayPIM: 16,
      awayFOW: 7,
      awaySOG: 8,
      awaySPG: 2,
      awaySaves: 10,
      awayGA: 1,
      awaySavesPerShot: 0.9090909090909091,
      awayPP_perc: 0,
      awaySH_perc: 0.5,
      awayPPG: 0,
      awaySHG: 0,
      awayPPGA: 0,
      awaySHGA: 1,
      awayNumPP: 1,
      awayNumSH: 2,
      awayHits: 7,
      awayPPSOG: 1,
      awayactiontype: 'api',
      awayteamId: 'ee93-ee93uy4oW',
      startDateTime: '',
      endDateTime: '',
      statusString: 'Slut',
      homeTeamId: 'VLH',
      homeTeamName: 'Växjö Lakers',
      homeG: 1,
      homePIM: 4,
      homeFOW: 9,
      homeSOG: 11,
      homeSPG: 3,
      homeSaves: 8,
      homeGA: 0,
      homeSavesPerShot: 1,
      homePP_perc: 0.5,
      homeSH_perc: 1,
      homePPG: 1,
      homeSHG: 0,
      homePPGA: 0,
      homeSHGA: 0,
      homeNumPP: 2,
      homeNumSH: 1,
      homeHits: 2,
      homePPSOG: 4,
      homeactiontype: 'api',
      hometeamId: 'fe02-fe02mf1FN'
    },
    '2': {
      periodNumber: 3,
      gameStatsId: 13558,
      status: 'Finished',
      awayTeamId: 'RBK',
      awayTeamName: 'Rögle BK',
      awayG: 1,
      awayPIM: 2,
      awayFOW: 12,
      awaySOG: 10,
      awaySPG: 8,
      awaySaves: 5,
      awayGA: 5,
      awaySavesPerShot: 0.625,
      awayPP_perc: 0,
      awaySH_perc: 0,
      awayPPG: 0,
      awaySHG: 0,
      awayPPGA: 0,
      awaySHGA: 1,
      awayNumPP: 1,
      awayNumSH: 1,
      awayHits: 5,
      awayPPSOG: 2,
      awayactiontype: 'api',
      awayteamId: 'ee93-ee93uy4oW',
      startDateTime: '',
      endDateTime: '',
      statusString: 'Slut',
      homeTeamId: 'VLH',
      homeTeamName: 'Växjö Lakers',
      homeG: 5,
      homePIM: 2,
      homeFOW: 8,
      homeSOG: 10,
      homeSPG: 2,
      homeSaves: 9,
      homeGA: 1,
      homeSavesPerShot: 0.9,
      homePP_perc: 1,
      homeSH_perc: 1,
      homePPG: 1,
      homeSHG: 0,
      homePPGA: 0,
      homeSHGA: 0,
      homeNumPP: 1,
      homeNumSH: 1,
      homeHits: 1,
      homePPSOG: 2,
      homeactiontype: 'api',
      hometeamId: 'fe02-fe02mf1FN'
    },
    gameRecap: {
      periodNumber: 0,
      gameStatsId: 13558,
      status: 'GameEnded',
      awayTeamId: 'RBK',
      awayTeamName: 'Rögle BK',
      awayG: 2,
      awayPIM: 18,
      awayFOW: 24,
      awaySOG: 27,
      awaySPG: 16,
      awaySaves: 20,
      awayGA: 6,
      awaySavesPerShot: 0.8333333333333334,
      awayPP_perc: 0,
      awaySH_perc: 0.3333333333333333,
      awayPPG: 0,
      awaySHG: 0,
      awayPPGA: 0,
      awaySHGA: 2,
      awayNumPP: 3,
      awayNumSH: 3,
      awayHits: 19,
      awayPPSOG: 4,
      awayactiontype: 'api',
      awayteamId: 'ee93-ee93uy4oW',
      startDateTime: '',
      endDateTime: '',
      statusString: 'Slut',
      statsId: 13558,
      round: 22,
      attendance: 8,
      homeTeamId: 'VLH',
      homeTeamName: 'Växjö Lakers',
      homeG: 6,
      homePIM: 8,
      homeFOW: 24,
      homeSOG: 26,
      homeSPG: 8,
      homeSaves: 25,
      homeGA: 2,
      homeSavesPerShot: 0.9259259259259259,
      homePP_perc: 0.6666666666666666,
      homeSH_perc: 1,
      homePPG: 2,
      homeSHG: 0,
      homePPGA: 0,
      homeSHGA: 0,
      homeNumPP: 3,
      homeNumSH: 3,
      homeHits: 4,
      homePPSOG: 6,
      homeactiontype: 'api',
      hometeamId: 'fe02-fe02mf1FN'
    }
  },
  gameState: 'GameEnded'
}
*/

interface GameStats {
    recaps: {
        0: Period,
        1: Period,
        2: Period,
        gameRecap: Period,
    },
    gameState: string,
    playersByTeam?: [],
}

interface Period {
    periodNumber: number,
    awayG: number,
    homeG: number,
    awayHits: number,
    homeHits: number,
    awaySOG: number,
    homeSOG: number,
}